; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
; board = esp32-c3-devkitc-02
; board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit_VL53L0X@^1.2.5

board_build.filesystem = littlefs
; board_build.partitions = default_4MB.csv   ; or min_spiffs.csv if you prefer

build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

build_src_filter = -<wifi_diag.cpp> +<main.cpp> -<I2C_check.cpp> -<main1.cpp> -<wifi_scanner.cpp> -<wifi_test.cpp>


