; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps = 
    adafruit/Adafruit_VL53L0X@^1.2.5

board_build.filesystem = littlefs
; board_build.partitions = default_4MB.csv   ; here you can change the file name

; Install mklittlefs tool automatically
platform_packages =
    tool-mklittlefs@~1.203.0

; ; Use mklittlefs for build/download/uploadfs targets
; extra_scripts =
;     pre:extra_script.py


build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

build_src_filter = +-<main.cpp> -<wifi_diag.cpp> -<I2C_check.cpp> -<wifi_scanner.cpp> -<wifi_test.cpp>



