; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; [env:esp32c3]
; platform = espressif32
; board = esp32-c3-devkitm-1
; framework = arduino
; monitor_speed = 115200
; monitor_filters = esp32_exception_decoder

; ; NO NEED for PSRAM cache fix on C3
; ; build_flags = 
; ;     -DBOARD_HAS_PSRAM
; ;     -mfix-esp32-psram-cache-issue   ← REMOVE THIS LINE

; lib_deps = 
;     mikalhart/TinyGPSPlus@^1.0.2
;     adafruit/Adafruit MPU6050@^2.2.4
;     adafruit/Adafruit BusIO@^1.16.1
;     adafruit/Adafruit Unified Sensor@^1.1.14



[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; No need for custom partitions on C3 Super Mini (4 MB flash default is fine)
; board_build.partitions = default_4MB.csv   ← REMOVE or COMMENT this line

lib_deps = 
    mikalhart/TinyGPSPlus@^1.0.2
    adafruit/Adafruit MPU6050@^2.2.4
    adafruit/Adafruit BusIO@^1.16.1
    adafruit/Adafruit Unified Sensor@^1.1.14

; Enable USB CDC (Serial) on boot
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -DLITTLEFS_PARTITION_LABEL=littlefs
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
    

; Enable LittleFS support
lib_ldf_mode = deep+

board_build.filesystem = littlefs

   

build_src_filter = +<main_p1.cpp> -<Board-Test.cpp> -<SDcard-test.cpp>